sequenceDiagram
    autonumber
    actor U as WaxLabs User
    participant D as Draft/Failed Draft
    participant F as Failed

    U->>D: Draft a new proposal

    create participant Dv as Deliverables
    D->>Dv: Adding Deliverables

    loop Add new/edit/remove deliverables
        Dv->>Dv:
    end

    participant S as Submit
    Dv->>S:  Submit to the WaxLabs admin

    participant R as Proposal Review
    S-->>R:  Proposal submitted

    participant I as In Progress
    participant Ac as Accepted
    participant C as Claimed

    R->>R: Admin Set the Proposal Reviewer

    rect rgb(191, 223, 255)
        critical Admin revision
            R-->>I: Aproves proposal
        option
            R-->>Ac: Approve with Voting
        option
            R-->>D: Rejects proposal with editing
        option
            rect rgb(255, 100, 100)
                break Proposal can't be changed
                    R-->>F: Rejects proposal
                end
            end
        end
    end

    create participant V as In Voting
    Ac-->>V: Begin Voting
    rect rgb(255, 223, 255)
        critical Community voting
            V->>I: Voting passed
        option
            V->>F: Voting failed
        end
    end

    U->>I: Submit Report for Deliverable

    create actor Rr as WaxLabs Reviewer
    I-->Rr: Review Deliverable
    Rr->>Rr: Review Deliverable

    rect rgb(255, 223, 100)
        critical Reviewer approval
            Rr->>C: Approved
        option
            Rr->>F: Failed
        end
    end


    loop Claim Deliverable until finished
        C->>U: Claim Deliverable
    end

    I->>Completed: Proposal Completed

