"""empty message

Revision ID: 530d4c301abf
Revises: 71b459df86bc
Create Date: 2023-10-08 17:28:37.320757

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "530d4c301abf"
down_revision: Union[str, None] = "71b459df86bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("proposals", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("subscriptions", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("subscriptions", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("proposals", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###
