"""empty message

Revision ID: 71b459df86bc
Revises: c97287126e12
Create Date: 2023-10-08 16:54:54.716507

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71b459df86bc"
down_revision: Union[str, None] = "c97287126e12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_proposals_uuid"), "proposals", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_proposals_uuid"), "proposals", type_="unique")
    # ### end Alembic commands ###
