"""empty message

Revision ID: cff1bcd0f04c
Revises: a4623d1d6d0b
Create Date: 2023-10-10 08:44:22.008229

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cff1bcd0f04c"
down_revision: Union[str, None] = "a4623d1d6d0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("subscriptions", "proposal_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("subscriptions", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint("uq_subscriptions_proposal_id", "subscriptions", type_="unique")
    op.create_unique_constraint(op.f("uq_subscriptions_proposal_id"), "subscriptions", ["proposal_id", "user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_subscriptions_proposal_id"), "subscriptions", type_="unique")
    op.create_unique_constraint("uq_subscriptions_proposal_id", "subscriptions", ["proposal_id"])
    op.alter_column("subscriptions", "user_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("subscriptions", "proposal_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
